# Generated by Django 2.0.7 on 2018-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='photo',
            field=models.ImageField(null='TRUE', upload_to='clientes_fotos'),
        ),
    ]
