# Generated by Django 2.0.7 on 2018-08-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
