# Generated by Django 2.0.7 on 2018-07-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180803_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='salary',
        ),
        migrations.AddField(
            model_name='cliente',
            name='adress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Adress'),
        ),
    ]
